name: flip_clock_board
description: Flip Clock Board based on Flip Board by Ricardo Nogueira https://github.com/cc-nogueira/flip_board
version: 1.0.0
homepage: https://github.com/ilgex/flip_clock_board

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: